In [1]:
import pandas as pd
data = pd.read_csv("trends.csv")

In [2]:
data

      location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26955 rows x 5 columns]

In [3]:
data.shape

(26955, 5)

In [4]:
data.head()

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [5]:
data.tail()

      location  year category  rank                query
26950  Vietnam  2020   Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020   Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020   Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020   Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020   Là Gì?     5       Đông Lào là gì

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 26955 entries, 0 to 26954
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  26955 non-null  str
 1   year      26955 non-null  int64
 2   category  26955 non-null  str
 3   rank      26955 non-null  int64
 4   query     26955 non-null  str
dtypes: int64(2), str(3)
memory usage: 2.0 MB

In [7]:
data.describe()

               year         rank
count  26955.000000  26955.00000
mean    2015.243369      3.00000
std        3.564683      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000

In [8]:
data.size

134775

In [9]:
data.isnull()

       location   year  category   rank  query
0         False  False     False  False  False
1         False  False     False  False  False
2         False  False     False  False  False
3         False  False     False  False  False
4         False  False     False  False  False
...         ...    ...       ...    ...    ...
26950     False  False     False  False  False
26951     False  False     False  False  False
26952     False  False     False  False  False
26953     False  False     False  False  False
26954     False  False     False  False  False

[26955 rows x 5 columns]

In [10]:
data.median

<bound method DataFrame.median of       location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26955 rows x 5 columns]>

In [11]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
26950    False
26951    False
26952    False
26953    False
26954    False
Length: 26955, dtype: bool

In [12]:
print(data.duplicated())

0        False
1        False
2        False
3        False
4        False
         ...
26950    False
26951    False
26952    False
26953    False
26954    False
Length: 26955, dtype: bool

In [13]:
data.duplicated().sum()

np.int64(10)

In [14]:
print(data.duplicated().sum())

10

In [15]:
data.drop_duplicates(inplace=True)

In [16]:
data

      location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26945 rows x 5 columns]

In [17]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
26950    False
26951    False
26952    False
26953    False
26954    False
Length: 26945, dtype: bool

In [18]:
print(data.duplicated().sum())

0

In [19]:
data.dtypes

location      str
year        int64
category      str
rank        int64
query         str
dtype: object

In [20]:
data

      location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26945 rows x 5 columns]

In [21]:
data.describe()

               year         rank
count  26945.000000  26945.00000
mean    2015.241974      3.00000
std        3.564557      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000

In [22]:
data.describe()

               year         rank
count  26945.000000  26945.00000
mean    2015.241974      3.00000
std        3.564557      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000